Pokedex = {
    "bulbasaur" =  {num=  1, to="ivysaur", at=16, egg={"monster", "grass"}},
    "ivysaur" =    {num=  2, to="venusaur", at=32},
    "venusaur" =   {num=  3},
    "charmander" = {num=  4, to="charmeleon", at=16, egg={"monster", "dragon"}},
    "charmeleon" = {num=  5, to="charizard", at=36},
    "charizard" =  {num=  6},
    "squirtle" =   {num=  7, to="wartortle", at=16, egg={"monster", "water 1"}},
    "wartortle" =  {num=  8, to="blastoise", at=36},
    "blastoise" =  {num=  9},
    "caterpie" =   {num= 10, to="metapod", at=7, egg={"bug"}},
    "metapod" =    {num= 11, to="butterfree", at=10},
    "butterfree" = {num= 12},
    "weedle" =     {num= 13, to="kakuna", at=7, egg={"bug"}},
    "kakuna" =     {num= 14, to="beedrill", at=10},
    "beedrill" =   {num= 15},
    "pidgey" =     {num= 16, to="pidgeotto", at=18, egg={"flying"}},
    "pidgeotto" =  {num= 17, to="pidgeot", at=36},
    "pidgeot" =    {num= 18},
    "rattatta" =   {num= 19, to="raticate", at=20, egg={"field"}},
    "raticate" =   {num= 20},
    "spearow" =    {num= 21, to="fearow", at=20, egg={"flying"}},
    "fearow" =     {num= 22},
    "ekans" =      {num= 23, to="arbok", at=22, egg={"field", "dragon"}},
    "arbok" =      {num= 24},
    "pikachu" =    {num= 25, to="raichu", at="thunderstone", egg={"field", "fiary"}},
    "raichu" =     {num= 26},
    "sandshrew" =  {num= 27, to="sandslash", at=22, egg={"field"}},
    "sandslash" =  {num= 28},
    "nidoranf" =   {num= 29, to="nidorina", at=16, egg={"monster", "field"}},
    "nidorina" =   {num= 30, to="nidoqueen", at="moonstone"},
    "nidoqueen" =  {num= 31},
    "nidoranm" =   {num= 32, to="nidorino", egg={"monster", at=16, "field"}},
    "nidorino" =   {num= 33, to="nidoking", at="moonstone"},
    "nidoking" =   {num= 34},
    "clefairy" =   {num= 35, to="clefable", at="moonstone", egg={"fairy"}},
    "clefable" =   {num= 36},
    "vulpix" =     {num= 37, to="ninetails", at="firestone", egg={"field"}},
    "ninetails" =  {num= 38},
    "jigglypuff" = {num= 39, to="wigglytuff", at="moonstone", egg={"fairy"}},
    "wigglytuff" = {num= 40},
    "zubat" =      {num= 41, to="golbat", at=22, egg={"flying"}},
    "golbat" =     {num= 42},
    "oddish" =     {num= 43, to="gloom", at=21, egg={"grass"}},
    "gloom" =      {num= 44, to="vileplume", at="leafstone"},
    "vileplume" =  {num= 45},
    "paras" =      {num= 46, to="parasect", at=24, egg={"bug", "grass"}},
    "parasect" =   {num= 47},
    "venonat" =    {num= 48, to="venomoth", at=31, egg={"bug"}},
    "venomoth" =   {num= 49},
    "diglet" =     {num= 50, to="dugtrio", at=26, egg={"field"}},
    "dugtrio" =    {num= 51},
    "meowth" =     {num= 52, to="persian", at=28, egg={"field"}},
    "persian" =    {num= 53},
    "psyduck" =    {num= 54, to="golduck", at=33, egg={"water 1", "field"}},
    "golduck" =    {num= 55},
    "mankey" =     {num= 56, to="primeape", at=28, egg={"field"}},
    "primeape" =   {num= 57},
    "growlithe" =  {num= 58, to="arcanine", at="firestone", egg={"field"}},
    "arcanine" =   {num= 59},
    "poliwag" =    {num= 60, to="poliwhirl", at=25, egg={"water 1"}},
    "poliwhirl" =  {num= 61, to="poliwrath", at="waterstone"},
    "poliwrath" =  {num= 62},
    "abra" =       {num= 63, to="kadabra", at=16, egg={"human-like"}},
    "kadabra" =    {num= 64, to="alakazam", at="trade"},
    "alakazam" =   {num= 65},
    "machop" =     {num= 66, to="machoke", at=28, egg={"human-like"}},
    "machoke" =    {num= 67, to="machamp", at="trade"},
    "machamp" =    {num= 68},
    "bellsprout" = {num= 69, to="weepinbell", at=21, egg={"grass"}},
    "weepinbell" = {num= 70, to="victreebel", at="leafstone"},
    "victreebel" = {num= 71},
    "tentacool" =  {num= 72, to="tentacreul", at=30, egg={"water 3"}},
    "tentacreul" = {num= 73},
    "geodude" =    {num= 74, to="graveler", at=25, egg={"mineral"}},
    "graveler" =   {num= 75, to="golem", at="trade"},
    "golem" =      {num= 76},
    "ponyta" =     {num= 77, to="rapidash", at=40, egg={"field"}},
    "rapidash" =   {num= 78},
    "slowpoke" =   {num= 79, to="slowbro", at=37, egg={"monster", "water 1"}},
    "slowbro" =    {num= 80},
    "magnemite" =  {num= 81, to="magneton", at=30, egg={"mineral"}},
    "magneton" =   {num= 82},
    "farfetchd" =  {num= 83, egg={"flying"}},
    "doduo" =      {num= 84, to="dodrio", at=31, egg={"flying"}},
    "dodrio" =     {num= 85},
    "seel" =       {num= 86, to="dewgong", at=34, egg={"water 1"}},
    "dewgong" =    {num= 87},
    "grimer" =     {num= 88, to="muk", at=38, egg={"amorphous"}},
    "muk" =        {num= 89},
    "shellder" =   {num= 90, to="cloyster", at="waterstone", egg={"water 3"}},
    "cloyster" =   {num= 91},
    "gastly" =     {num= 92, to="haunter", at=25, egg={"amorphous"}},
    "haunter" =    {num= 93, to="gengar", at="trade"},
    "gengar" =     {num= 94},
    "onyx" =       {num= 95, egg={"mineral"}},
    "drowzee" =    {num= 96, to="hypno", at=26, egg={"human-like"}},
    "hypno" =      {num= 97},
    "krabby" =     {num= 98, to="kingler", at=28, egg={"water 3"}},
    "kingler" =    {num= 99},
    "voltorb" =    {num=100, to="electrode", at=30, egg={"mineral"}},
    "electrode" =  {num=101},
    "exeggcute" =  {num=102, to="exeggutor", at="leafstone", egg={"grass"}},
    "exeggutor" =  {num=103},
    "cubone" =     {num=104, to="marowak", at=28, egg={"monster"}},
    "marowak" =    {num=105},
    "hitmonlee" =  {num=106, egg={"human-like"}},
    "hitmonchan" = {num=107, egg={"human-like"}},
    "lickitung" =  {num=108, egg={"monster"}},
    "koffing" =    {num=109, to="weezing", at=35, egg={"amorphous"}},
    "weezing" =    {num=110},
    "ryhorn" =     {num=111, to="rhydon", at=42, egg={"monster", "field"}},
    "rhydon" =     {num=112},
    "chansey" =    {num=113, egg={"fairy"}},
    "tangela" =    {num=114, egg={"grass"}},
    "kangaskhan" = {num=115, egg={"monster"}},
    "horsea" =     {num=116, to="seadra", at=32, egg={"water 1", "dragon"}},
    "seadra" =     {num=117},
    "goldeen" =    {num=118, to="seaking", at=33, egg={"water 2"}},
    "seaking" =    {num=119},
    "staryu" =     {num=120, to="starmie", at="waterstone", egg={"water 3"}},
    "starmie" =    {num=121},
    "mrmime" =     {num=122, egg={"human-like"}},
    "scyther" =    {num=123, egg={"bug"}},
    "jynx" =       {num=124, egg={"human-like"}},
    "electabuzz" = {num=125, egg={"human-like"}},
    "magmar" =     {num=126, egg={"human-like"}},
    "pinsir" =     {num=127, egg={"bug"}},
    "tauros" =     {num=128, egg={"field"}},
    "magikarp" =   {num=129, to="gyrados", at=20, egg={"water 2"}},
    "gyrados" =    {num=130},
    "lapras" =     {num=131, egg={"monster", "water 1"}},
    "ditto" =      {num=132, egg={"ditto"}},
    "eevee" =      {num=133, to={"vaporeon","jolteon","flareon"}, at="eevee", egg={"field"}},
    "vaporeon" =   {num=134},
    "jolteon" =    {num=135},
    "flareon" =    {num=136},
    "porygon" =    {num=137, egg={"mineral"}},
    "omanyte" =    {num=138, to="omastar", at=40, egg={"water 1", "water 3"}},
    "omastar" =    {num=139},
    "kabuto" =     {num=140, to="kabutops", at=40, egg={"water 1", "water 3"}},
    "kabutops" =   {num=141},
    "aerodactyl" = {num=142, egg={"flying"}},
    "snorlax" =    {num=143, egg={"monster"}},
    "articuno" =   {num=144, egg={"legend"}},
    "zapdos" =     {num=145, egg={"legend"}},
    "moltres" =    {num=146, egg={"legend"}},
    "dratini" =    {num=147, to="dragonair", at=30, egg={"water 1", "dragon"}},
    "dragonair" =  {num=148, to="dragonite", at=55},
    "dragonite" =  {num=149},
    "mewtwo" =     {num=150, egg={"legend"}},
    "mew" =        {num=151, egg={"legend"}}
}
